defaults:
  - _self_

hydra:
  run:
    dir: outputs/sft/${now:%Y-%m-%d}/${now:%H-%M-%S}
  searchpath:
    - pkg://rllm.experimental.config

tinker_base_url: null

# Required: short description of what's new in this run, e.g.:
#   run_name="top3-cot-bs512"
#   run_name="top3-cot-depth25"
run_name: ???

model:
  name: "Qwen/Qwen3.5-35B-A3B"
  lora_rank: 32
  train_unembed: true
  train_attn: true
  train_mlp: true

trainer:
  total_epochs: 1
  logger: ["console", "ui"]
  project_name: "chess-sft"
  experiment_name: "sft-${run_name}"
  default_local_dir: "checkpoints/sft/${run_name}"
  save_freq: 50
  test_freq: 500

data:
  train_files: null
  val_files: null
  train_batch_size: 512
  micro_batch_size_per_gpu: 512
  train_max_samples: -1
  max_length: 256
  val_max_samples: 320
  renderer_name: "qwen3"
  rllm:
    tokenize_and_mask_method: "stepwise"  # use LAST_ASSISTANT_MESSAGE to avoid renderer extension warning

optim:
  lr: 1.0e-3
  lr_scheduler: "cosine"
  betas: [0.9, 0.95]
  eps: 1e-8
